
"use client";

import './globals.css';
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from '@/contexts/AuthContext';
import { usePathname, useRouter } from 'next/navigation';
import { useAuth } from '@/contexts/AuthContext';
import { useEffect } from 'react';

// This component is no longer needed as individual pages handle auth checks.
// const AuthGatedLayout = ({ children }: { children: React.ReactNode }) => {
//   const { currentUser, loading } = useAuth();
//   const router = useRouter();
//   const pathname = usePathname();

//   useEffect(() => {
//     if (!loading && !currentUser && pathname !== '/' && pathname !== '/signup') {
//       router.push('/');
//     }
//   }, [currentUser, loading, router, pathname]);

//   return <>{children}</>;
// }


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>RaveWave</title>
        <meta name="description" content="Generated by Firebase Studio" />
      </head>
      <body className="font-body antialiased">
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
